//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AracTipleri
    {
        public int AracTipiID { get; set; }
        public string AracTipi { get; set; }
    }
}
