//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OtoparOtomasyon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkYeri
    {
        public int ParkYeriID { get; set; }
        public bool ParkDurumu { get; set; }
        public int AboneID { get; set; }
        public Nullable<System.DateTime> TarihGiriş { get; set; }
        public Nullable<System.DateTime> TarihÇıkış { get; set; }
    
        public virtual Aboneler Aboneler { get; set; }
    }
}
